# Generated by Django 3.2.8 on 2022-04-11 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='název')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='popis')),
            ],
            options={
                'verbose_name': 'kategorie',
                'verbose_name_plural': 'kategorie',
            },
        ),
        migrations.CreateModel(
            name='LikertScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='název')),
                ('choices', models.TextField(help_text='Zadejte možné odpovědi na otázku oddělené čárkou.', verbose_name='odpovědi')),
                ('scores', models.TextField(help_text='Zadejte bodové hodnocení každé odpovědi na otázku oddělené čárkou.', verbose_name='skóre odpovědí')),
            ],
            options={
                'verbose_name': 'likertova škála',
                'verbose_name_plural': 'likertovy škály',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='název')),
                ('short_name', models.CharField(help_text='Např.: OMSAT-3*, ACSI-28 apod.', max_length=30, verbose_name='zkratka názvu')),
                ('description', models.TextField(verbose_name='popis')),
                ('instructions', models.TextField(verbose_name='instrukce')),
                ('is_published', models.BooleanField(default=False, verbose_name='zvěřejněný')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='smazaný')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='datum smazání')),
            ],
            options={
                'verbose_name': 'dotazník',
                'verbose_name_plural': 'dotazníky',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on_date', models.DateTimeField(auto_now_add=True, verbose_name='datum vyžádání responze')),
                ('responded_on_date', models.DateTimeField(null=True, verbose_name='datum responze')),
                ('is_pending', models.BooleanField(default=True, verbose_name='čeká se na reponzi')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='klient')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='sportdiag.survey', verbose_name='dotazník')),
            ],
            options={
                'verbose_name': 'žádost o responzi',
                'verbose_name_plural': 'žádosti o responze',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='datum vytvoření')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sportdiag.survey', verbose_name='dotazník')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='uživatel')),
            ],
            options={
                'verbose_name': 'Set of answers to survey',
                'verbose_name_plural': 'Sets of answers to surveys',
            },
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='název')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='popis')),
                ('instructions', models.TextField(verbose_name='instrukce')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='sportdiag.survey', verbose_name='dotazník')),
            ],
            options={
                'verbose_name': 'skupina',
                'verbose_name_plural': 'skupiny',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text otázky')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='číslo otázky')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='pořadí v dotazníku')),
                ('required', models.BooleanField(verbose_name='povinná odpověď')),
                ('choices', models.TextField(blank=True, help_text='Zadejte možné odpovědi na otázku oddělené čárkou.', null=True, verbose_name='odpovědi')),
                ('scores', models.TextField(default=0, help_text='Zadejte bodové hodnocení každé odpovědi na otázku oddělené čárkou. V případě, že otázka není bodově hodnocena, zadejte "0" (bez uvozovek).', verbose_name='skóre odpovědí')),
                ('type', models.CharField(choices=[('short_text', 'krátký text (jeden řádek)'), ('radio', 'výběr jedné odpovědi'), ('select', 'výběr jedné odpovědi ze seznamu'), ('integer', 'celé číslo'), ('likert_scale', 'likertova škála')], default='short_text', max_length=100, verbose_name='typ otázky')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='sportdiag.category', verbose_name='kategorie')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='sportdiag.questiongroup', verbose_name='skupina')),
                ('likert_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='sportdiag.likertscale', verbose_name='likertova škála')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sportdiag.survey', verbose_name='dotazník')),
            ],
            options={
                'verbose_name': 'otázka',
                'verbose_name_plural': 'otázky',
            },
        ),
        migrations.AddField(
            model_name='likertscale',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likert_scales', to='sportdiag.questiongroup', verbose_name='skupina'),
        ),
        migrations.AddField(
            model_name='likertscale',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likert_scales', to='sportdiag.survey', verbose_name='dotazník'),
        ),
        migrations.AddField(
            model_name='category',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sportdiag.survey', verbose_name='dotazník'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='datum vytvoření')),
                ('body', models.TextField(blank=True, null=True, verbose_name='odpověď')),
                ('score', models.IntegerField(default=0, verbose_name='skóre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sportdiag.question', verbose_name='otázka')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sportdiag.response', verbose_name='responze')),
            ],
        ),
    ]
