# Generated by Django 3.2.8 on 2022-04-11 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('sportdiag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='interview_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='unikátní ID responze'),
        ),
    ]
