# Generated by Django 3.2.8 on 2022-04-11 14:34

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Response = apps.get_model('sportdiag', 'Response')
    for row in Response.objects.all():
        row.interview_uuid = uuid.uuid4()
        row.save(update_fields=['interview_uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('sportdiag', '0002_response_interview_uuid'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid),  # reverse_code=migrations.RunPython.noop
    ]
