# Generated by Django 3.2.8 on 2022-04-16 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportdiag', '0004_remove_response_interview_uuid_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='short_name',
        ),
        migrations.AddField(
            model_name='survey',
            name='type',
            field=models.CharField(choices=[('ACSI-28-REFEREE', 'ASCI-28 pro rozhodčí'), ('ACSI-28-ATHLETE', 'ASCI-28 pro sportovce'), ('PCDEQ', 'PCDEQ'), ('VMIQ-2', 'VIMQ-2'), ('OMSAT-3*', 'OMSAT-3* modifikovaná verze')], default='ACSI-28-REFEREE', max_length=60, verbose_name='Typ/Metoda'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='popis'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sportdiag.category', verbose_name='kategorie'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveIntegerField(default=0, help_text='Pokud otázka nespadá do žádné hodnocené kategorie (dimenze, škály, ...), nastavte číslo na 0.', verbose_name='číslo otázky'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='popis'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='instrukce'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='accounts.user', verbose_name='uživatel'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='instrukce'),
        ),
        migrations.AlterField(
            model_name='surveyresponserequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_requests', to=settings.AUTH_USER_MODEL, verbose_name='klient'),
        ),
        migrations.AlterField(
            model_name='surveyresponserequest',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_requests', to='sportdiag.survey', verbose_name='dotazník'),
        ),
    ]
