# Generated by Django 3.2.8 on 2022-04-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportdiag', '0005_auto_20220416_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likertscale',
            name='choices',
            field=models.TextField(help_text='Zadejte možné odpovědi likertovi škály oddělené čárkou. Např. téměř nikdy, někdy, často, téměř vždy', verbose_name='odpovědi'),
        ),
        migrations.AlterField(
            model_name='likertscale',
            name='scores',
            field=models.TextField(help_text='Zadejte bodové hodnocení každé odpovědi oddělené čárkou. Např. 0,1,2,3', verbose_name='skóre odpovědí'),
        ),
    ]
