# Generated by Django 3.2.8 on 2022-05-07 13:24

from django.db import migrations
from django.db import transaction
from sportdiag.models import Survey as _Survey
from sportdiag.models import Question as _Question

app_name = 'sportdiag'
survey_name = "Dotazník copingových dovedností ACSI-28 pro sportovce"


@transaction.atomic
def add_acsi28_athletes_survey(apps, schema_editor):
    Survey = apps.get_model(app_name, 'Survey')
    survey = Survey.objects.create(
        name=survey_name,
        description="""The Athletics Coping Skills Inventory – 28 (Smith et al., 1995) je standardizovaná 
        americká metoda, která se používá ke zjišťování úrovně copingových dovedností sportovců. 
        Americká verze se sestává z 28 otázek, které jsou koncipovány do sedmi konkrétních oblastí (škál). 
        Tyto oblasti představují jednotlivé mentální dovednosti sportovce. 
        Konkrétně se tedy jedná o Vyrovnávání se s nesnázemi, Dosažení maxima pod tlakem, 
        Stanovení cílů a Mentální přípravu, koncentraci, Důvěru v sebe sama a Dosažení motivace, 
        Schopnost akceptovat konstruktivní kritiku a Osvobození se od strachu.""",
        instructions="""Pozorně si prosím přečtěte každé tvrzení a vyberte jednu odpověď,
        se kterou se nejvíce ztotožňujete. V dotazníku nejsou žádné správné nebo špatné odpovědi. 
        Prosím, vyberte, jak často provádíte zmiňovanou činnost při vašem výkonu.""",
        is_published=True,
        type=_Survey.ACSI28_ATHLETE,
    )
    # add acsi28 athletes survey categories
    Category = apps.get_model(app_name, 'Category')
    categories = [
        Category(name="Zvládání zátěže a nesnází (Coping with Adversity)",
                 survey=survey,
                 description="""Rozhodčí, kteří získají vysoký počet bodů v této oblasti, 
                 zůstávají v dobrém psychickém rozpoložení i v případě neúspěchu apod. 
                 Komplikované situace mají pevně ve svých rukou a většinou je řeší v klidu a bez emocí. 
                 Mají také schopnost rychle se vzpamatovat a ponaučit se z vlastních chyb a neúspěchů."""
                 ),
        Category(name="Schopnost akceptovat konstruktivní kritiku (Coachability)",
                 survey=survey,
                 description="""Respondenti, kteří budou dosahovat vysokých hodnot u těchto položek, 
                 disponují schopností přijímat kritiku na svou osobu a berou si z ní ponaučení. 
                 Naučit se nové věci pro ně většinou nebývá problém a jsou otevření k daným připomínkám a instrukcím."""
                 ),
        Category(name="Koncentrace (Concentration)",
                 survey=survey,
                 description="""Lidé, kteří v tomto okruhu budou disponovat vysokým skóre, 
                 nemají problém udržet pozornost za jakékoliv nepříznivé situace. Mají schopnost plně 
                 se koncentrovat na konkrétní úkol i za ztížených a vypjatých podmínek."""
                 ),
        Category(name="Důvěra v sebe sama a motivace (Confidence and Motivation)",
                 survey=survey,
                 description="""Vysoké hodnoty v tomto případě ukazují na schopnost tvrdě na sobě pracovat, být 
                 pozitivně motivován, věřit ve své schopnosti a tím neustále posouvat hranice svých možností."""
                 ),
        Category(name="Vytyčení si cílů a psychická příprava (Goal Setting and Mental Preparation)",
                 survey=survey,
                 description="""Ten, kdo dosáhne nadprůměrných hodnot v této oblasti, se zodpovědně 
                 připravuje na výkon, dokáže si stanovit a pojmenovat konkrétní výkonnostní cíle. 
                 Má předem připravený plán, kterým se bude v průběhu utkání řídit."""
                 ),
        Category(name="Dosažení maxima pod tlakem (Peaking under Pressure)",
                 survey=survey,
                 description="""Rozhodčí, kteří budou v této subškále vykazovat vysokého bodového hodnocení,
                  se naučili pracovat pod tlakem a jsou schopni ve složitých situacích podávat 
                  nadprůměrné výkony. Během zátěže dosahují většího nasazení a pracovního úsilí."""
                 ),
        Category(name="Osvobození se od strachu (Freedom from Worry)",
                 survey=survey,
                 description="""Respondenti, kteří byli bodově úspěšní v tomto případě, si nedělají 
                 starosti z nepříznivých situací a chyb, které mohou nastat v průběhu utkání.
                 Tito lidé se tedy nevystavují předem zbytečnému tlaku. 
                 Nedělají si těžkou hlavu z kritiky ostatních v momentech, kdy chybu udělají, 
                 a zbytečně se nezaměřují na negativní situace, které nechtějí, aby se staly."""
                 ),
    ]
    for category in categories:
        category.save()
    # todo not working Category.objects.bulk_create(categories)
    # add acsi28 athletes survey questions
    Question = apps.get_model(app_name, 'Question')
    scores_asc = "0,1,2,3"
    scores_desc = "3,2,1,0"
    choices = "téměř nikdy, někdy, často, téměř vždy"
    questions = [
        # no category questions
        Question(text="Sport",
                 number=0,
                 order=1,
                 required=True,
                 type=_Question.SHORT_TEXT,
                 survey=survey,
                 scores="0"),
        Question(text="Současná úroveň, na které provozujete svůj sport",
                 number=0,
                 order=2,
                 required=True,
                 type=_Question.RADIO,
                 survey=survey,
                 choices="Regionální úroveň, Celonárodní úroveň, Mezinárodní reprezentace, Svůj sport aktivně neprovozuji",
                 scores="0,0,0,0"),
        Question(text="Nejvyšší úroveň, na které jste provozoval/a svůj sport",
                 number=0,
                 order=3,
                 required=True,
                 type=_Question.RADIO,
                 survey=survey,
                 choices="Regionální úroveň, Celonárodní úroveň, Mezinárodní reprezentace",
                 scores="0,0,0"),
        Question(text="Nejvyšší stupeň dokončeného vzdělání",
                 number=0,
                 order=4,
                 required=True,
                 type=_Question.SELECT,
                 survey=survey,
                 choices="Základní, Střední, Vyšší odborné, Vysokoškolské",
                 scores="0,0,0,0"),
        # categorized questions
        Question(text="Udržuji emoce pod kontrolou bez ohledu na to, jak se věci vyvíjí.",
                 number=24,
                 order=28,
                 required=True,
                 type=_Question.RADIO,
                 survey=survey,
                 choices=choices,
                 scores=scores_asc,
                 category=categories[0]),
        Question(text="Když cítím příliš velké napětí, dokážu rychle uvolnit tělo a uklidnit se.",
                 number=21,
                 order=25,
                 required=True,
                 type=_Question.RADIO,
                 survey=survey,
                 choices=choices,
                 scores=scores_asc,
                 category=categories[0]),
        Question(text="Když se věci vyvíjejí špatně, říkám si „zůstaň klidný“ a funguje mi to.",
                 number=17,
                 order=21,
                 required=True,
                 type=_Question.RADIO,
                 survey=survey,
                 choices=choices,
                 scores=scores_asc,
                 category=categories[0]),
        Question(
            text="Zůstávám pozitivně naladěný a nadšený během zápasu/závodu, bez ohledu na to, jak špatně se vyvíjí.",
            number=5,
            order=9,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[0]),
        #
        Question(
            text="Zlepšuji své dovednosti tím, že pozorně poslouchám rady a instrukce od zkušenějšího trenéra nebo mentora.",
            number=27,
            order=31,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[1]),
        Question(
            text="Když mě trenér kritizuje, příště napravím chybu bez toho, že bych se rozčílil.",
            number=15,
            order=19,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[1]),
        Question(
            text="Když mě trenér kritizují, spíše mě to rozčílí, než by mi to pomohlo.",
            number=10,
            order=14,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[1]),
        Question(
            text="Když mi trenér řekne, kde dělám chybu, mám tendenci si to brát osobně.",
            number=3,
            order=7,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[1]),
        #
        Question(
            text="Je pro mě jednoduché zaměřit pozornost a koncentrovat se na jednu věc nebo osobu.",
            number=25,
            order=29,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[2]),
        Question(
            text="S neočekávanými situacemi ve svém sportu se vyrovnávám velmi dobře.",
            number=16,
            order=20,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[2]),
        Question(
            text="Je pro mě jednoduché udržet rušivé myšlenky pod kontrolou a soustředit se na to co vidím nebo slyším.",
            number=11,
            order=15,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[2]),
        Question(
            text="Když podávám sportovní výkon, dokážu se soustředit a eliminovat rušivé vlivy.",
            number=4,
            order=8,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[2]),
        #
        Question(
            text="Když nedosáhnu svých cílů, přinutí mě to k ještě většímu úsilí.",
            number=26,
            order=30,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[3]),
        Question(
            text="Nemusí na mě nikdo tlačit, abych podával výkon na hranici svých možností, dávám tomu 100 %.",
            number=14,
            order=18,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[3]),
        Question(
            text="Věřím si, že podám dobrý výkon v zápase/závodě.",
            number=9,
            order=13,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[3]),
        Question(
            text="Dokážu zúročit svůj talent a dovednosti.",
            number=2,
            order=6,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[3]),
        #
        Question(
            text="Mám vypracovaný vlastní strategický plán v hlavě dlouho před tím, než zápas/závod začne.",
            number=20,
            order=24,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[4]),
        Question(
            text="Pro každý trénink si stanovuji osobní výkonnostní cíle.",
            number=13,
            order=17,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[4]),
        Question(
            text="Často plánuji, jak dosáhnout svých cílů.",
            number=8,
            order=12,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[4]),
        Question(
            text="Denně nebo týdně si stanovuji konkrétní cíle, které mi řídí moji činnosti.",
            number=1,
            order=5,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[4]),
        #
        Question(
            text="Dělám méně chyb, když jsem pod tlakem, protože se lépe koncentruji.",
            number=28,
            order=32,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[5]),
        Question(
            text="Zátěžové situace jsou pro mě výzvou a vítám je.",
            number=22,
            order=26,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[5]),
        Question(
            text="Čím více jsem podtlakem během zápasu/závodu, tím víc si to užívám.",
            number=18,
            order=22,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[5]),
        Question(
            text="Rozhoduji lépe pod tlakem, protože mám jasnou mysl.",
            number=6,
            order=10,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[5]),
        #
        Question(
            text="Myslím a představuji si, co se stane, když udělám chybu nebo neuspěji.",
            number=23,
            order=27,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[6]),
        Question(
            text="Během zápasu/závodu se bojím, abych neudělal špatné rozhodnutí, a mám strach z neúspěchu.",
            number=19,
            order=23,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[6]),
        Question(
            text="Vyvíjím na sebe velký tlak tím, jak moc mi záleží na mém výkonu.",
            number=12,
            order=16,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[6]),
        Question(
            text="Dost mi záleží na tom, co si ostatní myslí o mém výkonu.",
            number=7,
            order=11,
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[6]),
    ]
    Question.objects.bulk_create(questions)


@transaction.atomic
def revert_acsi28_athletes_survey(apps, schema_editor):
    Survey = apps.get_model(app_name, 'Survey')
    survey = Survey.objects.get(name=survey_name)
    if survey:
        survey.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('sportdiag', '0007_auto_20220507_1524'),
    ]

    operations = [
        migrations.RunPython(add_acsi28_athletes_survey, reverse_code=revert_acsi28_athletes_survey),
    ]
