# Generated by Django 3.2.8 on 2022-05-15 12:20

from django.db import migrations
from django.db import transaction
from sportdiag.models import Survey as _Survey
from sportdiag.models import Question as _Question
from bp.utils.migrations import integer_sequence

app_name = 'sportdiag'
survey_name = "Dotazník psychických vlastností nutných k rozvoji vyjímečnosti - PCDEQ"


@transaction.atomic
def add_pcdeq_survey(apps, schema_editor):
    Survey = apps.get_model(app_name, 'Survey')
    survey = Survey.objects.create(
        name=survey_name,
        description="""Dotazník PCDEQ (Psychological Characteristics of Developing Excellence 
        Questionnaire, MacNamara & Collins, 2011) je nástroj zjišťující přítomnost a úroveň 
        těchto vlastností u sportovců, u kterých je talent stále v procesu rozvoje. 
        Zaměřuje se na dospívající jedince ve věkovém rozmezí od 14 do 21 let. 
        Test se skládá z 59 položek, rozdělených na 6 faktorů (1. Podpora k dlouhodobému úspěchu,
         2. Používání imaginace během tréninku a soutěže, 3. Zvládání stresu spojeného
          s výkonem a rozvojem, 4. Schopnost organizovat kvalitní trénink a zapojit se do něj, 
          5. Vyhodnocování výkonů a práce na slabých stránkách, 
          6. Podpora od ostatních k podávání výkonů odpovídajících mému potenciálu).""",
        instructions="""Nejprve si přečti/ěte každý výrok a zakroužkuj/te číslo podle toho, 
        do jaké míry s daným výrokem souhlasíš/te. Neexistují dobré nebo špatné odpovědi, 
        odpovídej/te prosím upřímně a bezprostředně. Odpovídej/te v kontextu sportu, 
        kterému se věnuješ/te nejvíce.""",
        is_published=True,
        type=_Survey.PCDEQ,
    )
    # add survey categories
    Category = apps.get_model(app_name, 'Category')
    categories = [
        Category(name="Podpora k dlouhodobému úspěchu",
                 survey=survey,
                 description="""Je zaměřena na to, do jaké míry patřičné osoby (např. trenéři) 
                 podporují své svěřence k používání Psychických vlastností k rozvoji 
                 výjimečnosti v praxi na cestě k dlouhodobé úspěšnosti. Hodnotí, do jaké míry
                  jsou mladí sportovci ve svém prostředí k rozvoji těchto vlastností vedeni. 
                  Nehodnotí jejich vlastní zapojení."""
                 ),
        Category(name="Používání imaginace během tréninku a soutěže",
                 survey=survey,
                 description="""Tento faktor hodnotí míru schopnosti imaginace jedince. 
                 Cílí jak na schopnosti jejího použití při tréninku, tak před samotným výkonem."""
                 ),
        Category(name="Zvládání stresu spojeného s výkonem a rozvojem",
                 survey=survey,
                 description="""Faktor zjišťuje schopnost respondenta vyrovnávat se s tlakem 
                 rozvoje i soutěže. Zvládání soutěžního prostředí je silně spojeno s úrovní 
                 podaného výkonu."""
                 ),
        Category(name="Schopnost organizovat kvalitní trénink a zapojit se do něj",
                 survey=survey,
                 description="""Položky tohoto faktoru se vtahují k přístupu sportovce k jeho 
                 tréninku. Zkoumají jeho chování při tréninku a schopnost sám rozvíjet svoji 
                 výkonovou úroveň."""
                 ),
        Category(name="Vyhodnocování výkonů a práce na slabých stránkách",
                 survey=survey,
                 description="""Tento faktor zdůrazňuje důležitost schopnosti dívat se realisticky 
                 na vlastní výkony, ať už se jedná o výhry, nebo prohry. Zjišťuje úroveň této 
                 schopnosti a schopnost na ni navazující práce na slabých stránkách."""
                 ),
        Category(name="Podpora od ostatních k podávání výkonů odpovídajících mému potenciálu",
                 survey=survey,
                 description="""Tento faktor cílí na úroveň podpory k podávání odpovídajících 
                 výkonů, které se respondentovi dostává od ostatních (trenér, rodina apod.). 
                 V tomto kontextu by se trenéři neměli zaměřovat pouze na rozvoj 
                 dovedností u svých svěřenců, ale měli by u nich také prosazovat a rozvíjet 
                 psychické vlastnosti k rozvoji výjimečnosti."""
                 ),
    ]
    for category in categories:
        category.save()
    # add survey questions
    Question = apps.get_model(app_name, 'Question')
    choices = "zcela nesouhlasím, nesouhlasím, spíše nesouhlasím, spíše souhlasím, souhlasím, zcela souhlasím"
    scores = "1,2,3,4,5,6"
    number = integer_sequence(100)
    order_number = integer_sequence(100)
    questions = [
        # no category questions
        Question(text="Sport",
                 number=0,
                 order=next(order_number),
                 required=True,
                 type=_Question.SHORT_TEXT,
                 survey=survey,
                 scores="0"),
        Question(text="Současná úroveň, na které provozujete svůj sport",
                 number=0,
                 order=next(order_number),
                 required=True,
                 type=_Question.RADIO,
                 survey=survey,
                 choices="Regionální úroveň, Celonárodní úroveň, Mezinárodní reprezentace, Svůj sport aktivně neprovozuji",
                 scores="0,0,0,0"),
        Question(text="Nejvyšší úroveň, na které jste provozoval/a svůj sport",
                 number=0,
                 order=next(order_number),
                 required=True,
                 type=_Question.RADIO,
                 survey=survey,
                 choices="Regionální úroveň, Celonárodní úroveň, Mezinárodní reprezentace",
                 scores="0,0,0"),
        Question(text="Nejvyšší stupeň dokončeného vzdělání",
                 number=0,
                 order=next(order_number),
                 required=True,
                 type=_Question.SELECT,
                 survey=survey,
                 choices="Základní, Střední, Vyšší odborné, Vysokoškolské",
                 scores="0,0,0,0"),
    ]
    # categorized questions
    category_separator = "next category"
    cat_questions_texts = [
        "Můj trenér/učitel mě nabádá, abych vyhledával rady u patřičných osob.",
        "Já a můj trenér/učitel plánujeme na základě mého úspěchu v dlouhodobém časovém hledisku, nesoustředíme se jen na přítomnost.",
        "Můj trenér/učitel mi pomáhá, abych zůstával oddaný své disciplíně/aktivitě.",
        "Můj trenér/učitel hodnotí mé výkony vzhledem k dlouhodobým cílům, vedoucím k úspěchům v budoucnosti.",
        "Můj trenér/učitel mě připravuje na to, abych dokázal zvládat tlaky spojené s výkonem v soutěži.",
        "Můj trenér/učitel mi říkává, o co bych měl usilovat, a pomáhá mi se směřováním mých cílů.",
        "Můj trenér/učitel mi pomáhá rozeznávat, co je dobré a špatné na mých výkonech.",
        "Já a můj trenér/učitel sledujeme, kolik mám celkově povinností s cílem udržovat rovnováhu mezi školou a tréninkem.",
        "Spolu s mým trenérem/učitelem monitorujeme (zaznamenáváme) pokrok při plnění mých cílů.",
        "Můj trenér/učitel stanovuje moje cíle a společně pracujeme na jejich naplnění.",
        "Mohu se spolehnout na svého trenéra/učitele, že mě popožene v aktivitách, které nemám příliš v oblibě.",
        "Můj trenér/učitel mi pomáhá všímat si pokroku, kterého jsem dosáhl/a.",
        "Můj trenér/učitel mě vede k používání jasných zažitých postupů (rutin).",
        "Můj trenér/učitel mi pomáhá soustředit se při mém tréninku na stanovené cíle.",
        "Můj trenér/učitel plánuje trénink tak, abych pracoval převážně na svých slabých stránkách.",
        "Můj trenér/učitel mě nabádá, abych o věcech mluvil.",
        "Můj trenér/učitel se ujišťuje, že vím, jaké kroky musím dělat, abych se stále rozvíjel.",
        category_separator,
        "Používám imaginaci, abych upravil svůj fyzický výkon.",
        "Před tím, než se pokusím provést nějakou dovednost (pohyb), představím si, jak ji provádím.",
        "Mentální nácvik je součástí mého tréninku.",
        "Mentální nácvik výkonu mi napomáhá soustředit se na to, co musím udělat.",
        "Pravidelně si představuji pocity, které ve mně vyvolává dobrý výkon.",
        "Můj trenér/učitel se domnívá, že mentální trénink je důležitý.",
        "Před příchodem na místo, kde mám podat určitý výkon, jsem nabádán k tomu, abych provedl mentální nácvik tohoto výkonu.",
        "Představuji si sám/sama sebe, jak se zvládám vyrovnat s nabuzením a vzrušením spojeným se soutěží.",
        "Očekává se ode mně, že zahrnu imaginaci do svojí přípravy.",
        "Trénujeme překonávání obtíží, abych mohl zůstat sebejistý.",
        "Když musím udělat něco, z čeho mám obavy, představuji si, jak je překonám a úspěšně provedu svůj výkon.",
        "Jsem nabádán k tomu, abych si věci zkusil nejprve jen v hlavě",
        category_separator,
        "Připadá mi těžké soustředit se na sebe a na to, co musím dělat, a často se přistihnu, že přemýšlím nad tím, jak se vede ostatním závodníkům/soutěžícím.",
        "Když se stane něco neočekávaného, je pro mě skutečně obtížné přizpůsobit se nové situaci.",
        "Je pro mě těžké začlenit se do nové tréninkové skupiny.",
        "Pokud jsem pod tlakem školních povinností, nedokáži zabránit jeho negativnímu dopadu na můj výkon.",
        "Pokud mi připadá nějaký úkol těžký, často se přestávám snažit.",
        "Jsem přesvědčený, že prohráváním se nemůžete nic naučit.",
        "I drobný nezdar otřese mojí sebedůvěrou.",
        "Pokud udělám chybu, připadá mi těžké znovu se začít soustředit na daný úkol.",
        "Můj trenér/učitel mě netlačí do překonávání obtíží.",
        "Připadá mi těžké překonat pocity úzkosti při podávání výkonu.",
        "Často myslím na chyby, které jsem udělal, což narušuje můj výkon.",
        category_separator,
        "Pokračuji v tom, co musím dělat, i když se nikdo nedívá.",
        "Jsem ochotný na sobě skutečně tvrdě pracovat.",
        "Veškerý trénink, který podstupuji, mi dodává důvěru, že dokážu uspět.",
        "V průběhu tréninku blokuji rušivé myšlenky a plně soustředím svou pozornost na to, co musí být splněno.",
        "Můj před-soutěžní plán je jasně stanovený a pečlivě sledovaný.",
        "Při tréninku přemýšlím jen o tom, co během něj musím udělat, a na to se soustředím.",
        "Stanovuji si náročné cíle, na jejichž dosažení musím tvrdě pracovat.",
        category_separator,
        "Neustále hledám způsoby, jak se zlepšovat.",
        "Vždy mám stanoven minimálně jeden cíl, na jehož dosažení pracuji.",
        "Po výkonu, si jeho průběh přehrávám znovu v hlavě, abych přišel na to, co jsem udělal dobře a co špatně.",
        "Rozebírám své výkony, abych zjistil, co jsem udělal dobře a co špatně.",
        "Uvědomuji si své slabé stránky a při tréninku na nich tvrdě pracuji.",
        category_separator,
        "Před důležitým výkonem mě lidé kolem mě udržují soustředěného.",
        "Jsme nabádáni k tomu, abychom si v tréninkovém prostředí vzájemně pomáhali.",
        "Můj trenér/učitel mi pomáhá při tréninku zůstat soustředěný.",
        "Můj trenér/učitel mi pomáhá připravit se na neočekávané (situace, okolnosti, události).",
        "Lidé kolem mě mi pomáhají přizpůsobit se s nárokům mojí disciplíny/aktivity.",
        "Naslouchám lidem kolem sebe a učím se od nich.",
        "Můj trenér/učitel využívá trénink k budování mé důvěry ve vlastní schopnosti.",
    ]
    i = 0
    for text in cat_questions_texts:
        if text == category_separator:
            i += 1
            continue
        questions.append(Question(text=text,
                                  number=next(number),
                                  order=next(order_number),
                                  required=True,
                                  type=_Question.RADIO,
                                  survey=survey,
                                  choices=choices,
                                  scores=scores,
                                  category=categories[i]
                                  ))
    Question.objects.bulk_create(questions)


@transaction.atomic
def revert_pcdeq_survey(apps, schema_editor):
    Survey = apps.get_model(app_name, 'Survey')
    survey = Survey.objects.get(name=survey_name)
    if survey:
        survey.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('sportdiag', '0009_demo_data_acsi28_referee_survey'),
    ]

    operations = [
        migrations.RunPython(add_pcdeq_survey, reverse_code=revert_pcdeq_survey),
    ]
