# Generated by Django 3.2.8 on 2022-05-20 20:26

from django.db import migrations
from django.db import transaction
from sportdiag.models import Survey as _Survey
from sportdiag.models import Question as _Question
from bp.utils.migrations import integer_sequence

app_name = "sportdiag"
survey_name = "Dotazník týmové atmosféry (GEQ-CZ V1)"


@transaction.atomic
def add_geq_survey(apps, schema_editor):
    Survey = apps.get_model(app_name, "Survey")
    survey = Survey.objects.create(
        name=survey_name,
        description="""Dotazník týmové atmosféry (Group Environment Questionnaire - GEQ, Carron, Widmeyer, & Brawley, 1985) patří k mezinárodně uznávaným nástrojům pro sledování týmové koheze a byl původně validizován pro populaci sportovců v Severní Americe. Dotazník hodnotí týmovou kohezi pomocí čtyř hlavních dimenzí.""",
        instructions="""Následující výroky zjišťují Vaši zkušenost s týmem, do kterého patříte. Odpovězte prosím zaškrtnutím čísla na škále 1-9 (vůbec nesouhlasím - naprosto souhlasím).""",
        is_published=True,
        type=_Survey.GEQCZV1,
    )
    # add survey categories
    Category = apps.get_model(app_name, "Category")
    categories = [
        Category(
            name="Individuální atraktivita skupiny - sociální koheze (ATG-S)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            name="Individuální atraktivita skupiny - úkolová koheze (ATG-T)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            name="Skupinová integrace - sociální koheze (GI-S)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            name="Skupinová integrace - úkolová koheze (GI-T)",
            survey=survey,
            description="""DOPLNIT""",
        ),
    ]
    for category in categories:
        category.save()
    # add survey questions
    Question = apps.get_model(app_name, "Question")
    # TODO choices = "1 = vůbec nesouhlasím, 2, 3, 4, 5, 6, 7, 8, 9 = naprosto souhlasím"
    choices = "vůbec nesouhlasím, 2, 3, 4, 5, 6, 7, 8, naprosto souhlasím"
    scores_asc = "1,2,3,4,5,6,7,8,9"
    scores_desc = "9,8,7,6,5,4,3,2,1"
    order_number = integer_sequence(100)
    questions = [
        # no category questions
        Question(
            text="Sport",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.SHORT_TEXT,
            survey=survey,
            scores="0",
        ),
        Question(
            text="Název týmu/družstva/klubu",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.SHORT_TEXT,
            survey=survey,
            scores="0",
        ),
        Question(
            text="Jak dlouho provozujete tento sport (roky)",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.INTEGER,
            survey=survey,
            scores="0",
        ),
        Question(
            text="Kolik let jste členem současného týmu",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.INTEGER,
            survey=survey,
            scores="0",
        ),
        Question(
            text="Kolikrát týdně společně tŕenujete",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.INTEGER,
            survey=survey,
            scores="0",
        ),
        Question(
            text="Pozice v týmu (kapitán, herní post, jiné)",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.SHORT_TEXT,
            survey=survey,
            scores="0",
        ),
        Question(
            text="Kolik lidí je v týmu",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.INTEGER,
            survey=survey,
            scores="0",
        ),
        Question(
            text="Kolik měsíců máte současného trenéra(y)",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.INTEGER,
            survey=survey,
            scores="0",
        ),
        Question(
            text="Jak je Váš tým v této sezóně úspěšný (1 - velmi; 5 - vůbec)",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices="1, 2, 3, 4, 5",
            scores="0,0,0,0,0",
        ),
        Question(
            text="V jakém stádiu sezóny právě teď jste",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.SELECT,
            survey=survey,
            choices="Přípravné, Soutěžní, Přestávka",
            scores="0,0,0",
        ),
        # categorized questions
        Question(
            text="Nerad/a se účastním společných mimosportovních akcí našeho týmu.",
            number=1,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[0],
        ),
        Question(
            text="Nejsem spokojen/a s množstvím času, kdy jsem nasazen/a do soutěže.",
            number=2,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[1],
        ),
        Question(
            text="Po skončení sezóny mi lidé z týmu nebudou chybět.",
            number=3,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[0],
        ),
        Question(
            text="Nejsem spokojen/a s touhou našeho týmu vyhrávat.",
            number=4,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[1],
        ),
        Question(
            text="Několik lidí z týmu patří mezi mé nejlepší přátele.",
            number=5,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[0],
        ),
        Question(
            text="V našem týmu nemám dost příležitostí zlepšit svůj osobní výkon.",
            number=6,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[1],
        ),
        Question(
            text="Raději si vyjdu se svými přáteli než s lidmi z našeho týmu.",
            number=7,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[0],
        ),
        Question(
            text="Nemám rád/a styl hry našeho týmu.",
            number=8,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[1],
        ),
        Question(
            text="V současné době je pro mě náš tým tou nejdůležitější skupinou lidí.",
            number=9,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[0],
        ),
        Question(
            text="Náš tým je jednotný v úsilí dosáhnout stanoveného cíle.",
            number=10,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[3],
        ),
        Question(
            text="Lidé z našeho týmu si za zábavou vyjdou raději sami než jako tým.",
            number=11,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[2],
        ),
        Question(
            text="Každý člen týmu nese zodpovědnost za špatný výkon nebo prohru.",
            number=12,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[3],
        ),
        Question(
            text="S týmem si jdeme sednout do hospody jen výjimečně.",
            number=13,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[2],
        ),
        Question(
            text="Členové našeho týmu mají rozdílné představy o tom, čeho bychom měli společně dosáhnout.",
            number=14,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[3],
        ),
        Question(
            text="Náš tým by rád strávil nějaký čas společně i po skončení sezóny.",
            number=15,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[2],
        ),
        Question(
            text="Když má někdo problém v tréninku, celý tým se mu snaží pomoci, aby se dostal zpátky do hry.",
            number=16,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_asc,
            category=categories[3],
        ),
        Question(
            text="Mimo tréninky nemají členové našeho týmu spolu mnoho společného.",
            number=17,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[2],
        ),
        Question(
            text="V našem týmu není zvykem otevřeně hovořit o zodpovědnosti jednotlivých členů v zápase či v tréninku.",
            number=18,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[3],
        ),
    ]
    Question.objects.bulk_create(questions)


@transaction.atomic
def revert_geq_survey(apps, schema_editor):
    Survey = apps.get_model(app_name, "Survey")
    survey = Survey.objects.get(name=survey_name)
    if survey:
        survey.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("sportdiag", "0011_demo_data_vmiq_survey"),
    ]

    operations = [
        migrations.RunPython(add_geq_survey, reverse_code=revert_geq_survey),
    ]
