# Generated by Django 3.2.8 on 2024-05-26 11:28

from django.db import migrations
from django.db import transaction
from sportdiag.models import Survey as _Survey
from sportdiag.models import Question as _Question
from bp.utils.migrations import integer_sequence

app_name = "sportdiag"
survey_name = "Zkrácená škála stavu flow (S FSS)"


@transaction.atomic
def add_sfss_survey(apps, schema_editor):
    Survey = apps.get_model(app_name, "Survey")
    survey = Survey.objects.create(
        name=survey_name,
        description="""Zkrácená škála stavu flow (SHORT Flow State Scale, S FSS) je devíti položková, zkrácená verze dotazníku Flow State Scale 2 (FSS 2). Využívá se k posuzování prožívání flow bezprostředně po vykonání dané aktivity. Proto by měl respondent odpovědět na otázky dotazníku hned, jak to je po podaném výkonu možné.""",
        instructions="""Odpovězte prosím na následující otázky v návaznosti na váš prožitek během činnosti či aktivity, kterou jste právě vykonal/a. Otázky níže se vztahují k myšlenkám a pocitům, které jste během ní prožíval/a. Neexistují žádné správné ani špatné odpovědi. Nejprve popřemýšlejte, jak jste se cítil/a v průběhu aktivity/činnosti, poté odpovězte na otázky s využitím škály. Pro každou otázku vyberte odpověď, která nejlépe vystihuje váš prožitek.""",
        is_published=True,
        type=_Survey.SFSS,
    )
    # add survey categories
    Category = apps.get_model(app_name, "Category")
    categories = [
        Category(
            # name="Challenge-skill balance",
            name="Rovnováha mezi požadavky situace a schopnostmi jedince (Challenge-Skill Balance)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Action-awareness merging",
            name="Ponoření se do aktivity (Merging of Action and Awareness)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Clear goals",
            name="Jasné cíle (Clear Goals)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Unambiguous feedback",
            name="Bezprostřední zpětná vazba (Unambiguous Feedback)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Total concentration on the task at hand",
            name="Koncentrace pozornosti na samotnou činnost (Concentration on the Task at Hand)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Sense of control",
            name="Pocit kontroly nad provozovanou aktivitou (Sense of Control)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Loss of self-consciousness",
            name="Ztráta sebeuvědomění (Loss of Self-Consciousness)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Transformation of time",
            name="Transformace času (Transformation of Time)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Autotelic experience",
            name="Autotelic Experience (Autotelická osobnost)",
            survey=survey,
            description="""DOPLNIT""",
        ),
    ]
    for category in categories:
        category.save()
    # add survey questions
    Question = apps.get_model(app_name, "Question")
    scores = "1,2,3,4,5"
    choices = "rozhodně nesouhlasím, nesouhlasím, ani nesouhlasím/ani souhlasím, souhlasím, rozhodně souhlasím"
    order_number = integer_sequence(100)
    question_number = integer_sequence(10)
    questions = [
        # no category questions
        Question(
            text="Sport",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.SHORT_TEXT,
            survey=survey,
            scores="0",
        ),
        Question(
            text="Současná úroveň, na které provozujete svůj sport",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices="Regionální úroveň, Celonárodní úroveň, Mezinárodní reprezentace, Svůj sport aktivně neprovozuji",
            scores="0,0,0,0",
        ),
        Question(
            text="Nejvyšší úroveň, na které jste provozoval/a svůj sport",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices="Regionální úroveň, Celonárodní úroveň, Mezinárodní reprezentace",
            scores="0,0,0",
        ),
        Question(
            text="Nejvyšší stupeň dokončeného vzdělání",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.SELECT,
            survey=survey,
            choices="Základní, Střední, Vyšší odborné, Vysokoškolské",
            scores="0,0,0,0",
        ),
        Question(
            text="Mé odpovědi se vztahují k následující aktivitě/činnosti",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.SHORT_TEXT,
            survey=survey,
            scores="0",
        ),
        # categorized questions
        Question(
            text="Cítil jsem, že jsem dostatečně schopný zvládnout požadavky dané situace.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[0],
        ),
        Question(
            text="Dělal jsem věci spontánně a automaticky, aniž bych o tom musel přemýšlet.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[1],
        ),
        Question(
            text="Měl jsem jasnou představu, co jsem chtěl ďelat.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[2],
        ),
        Question(
            text="Během svého zapojení do aktivity/činnosti jsem měl jasnou představu o tom, jak dobře si v ní vedu.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[3],
        ),
        Question(
            text="Plně jsem se soustředil na danou činnost/aktivitu.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[4],
        ),
        Question(
            text="Pociťoval jsem plnou kontrolu nad tím, co dělám.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[5],
        ),
        Question(
            text="Neobával jsem se toho, co si o mě ostatní myslí.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[6],
        ),
        Question(
            text="Plynutí času mi připadalo jiné, než obvykle.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[7],
        ),
        Question(
            text="Považuji daný prožitek za velmi odměňující/obohacující.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[8],
        ),
    ]
    Question.objects.bulk_create(questions)


@transaction.atomic
def revert_sfss_survey(apps, schema_editor):
    Survey = apps.get_model(app_name, "Survey")
    survey = Survey.objects.get(name=survey_name)
    if survey:
        survey.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sportdiag", "0013_alter_survey_type"),
    ]

    operations = [
        migrations.RunPython(add_sfss_survey, reverse_code=revert_sfss_survey),
    ]
