# Generated by Django 3.2.8 on 2022-02-12 13:26

from django.db import migrations
from django.db import transaction

app_name = 'sportdiag'

# todo solve better, migrate command throws attribute error, probably doesnt see these atributes on Question model
SHORT_TEXT = "short_text"
RADIO = "radio"
SELECT = "select"
INTEGER = "integer"
LIKERT_SCALE = "likert_scale"


def integer_sequence(limit):
    current = 1
    while current < limit:
        yield current
        current += 1


omsat3_description = """Ottawský dotazník mentálních dovedností OMSAT-3* (Ottawa Mental Skills Assessment
Tool) je nástroj určen k měření široké škály psychických vlastností využívaných sportovci.
Tento nástroj vyvinuli Natalie Durand-Bushová a John Salmela pro posuzování mentálních
dovedností sportovců, jako například zvládání stresu, relaxace nebo imaginace. Jedná se o
dotazník, jehož validita a reliabilita je podložena řadou vědeckých výzkumů, současně je
prověřený i každodenní praxí. Informace získané prostřednictvím nástroje OMSAT poskytují
sportovcům obrázek o jejích mentálních dovednostech, které využívají v kontextu svého
sportu. To jim pomáhá identifikovat jejich silné stránky, na které se mohou při své psychické
přípravě spolehnout, ukázat jim cesty jak zdokonalit svůj výkon, nebo rozšířit jejich
povědomí o vzorcích optimálního výkonu. Sportovním psychologům nebo trenérům slouží
tento nástroj k tomu, aby si ověřili pocity a dojmy, které získali v průběhu své práce
s klientem či svěřencem, a vytvořili si tak o něm vyváženější a ucelenější představu.
V důsledku tak mohou přesněji přizpůsobit sportovní přípravu sportovce jeho individuálním
potřebám za účelem zvyšování jeho výkonnosti, a to jak z krátkodobého, tak dlouhodobého
hlediska.
OMSAT-3* zároveň v otázce mentální přípravy a připravenosti velmi dobře rozlišuje mezi
profesionálními a amatérskými sportovci. Dotazník byl vyvinut pro měření účinku programů
tréninku psychiky u sportovců (mentální příprava) a představuje užitečný doplněk
k jakýmkoliv metodám zlepšování výkonu. Může být použit pro získávání opakovaných
hodnocení. Lze jej využít i pro aktuální posouzení kvality psychické složky sportovního
talentu v rámci multidisciplinárního dynamického přístupu."""

omsat3_current_sport_level_choices = "Regionální úroveň, Celonárodní úroveň, Mezinárodní reprezentace, \
Svůj sport aktivně neprovozuji"
omsat3_max_sport_level_choices = "Regionální úroveň, Celonárodní úroveň, Mezinárodní reprezentace"
omsat3_education_choices = "Základní, Střední, Vyšší odborné, Vysokoškolské"
omsat3_likert_scale_choices = "1, 2, 3, 4, 5, 6, 7"


@transaction.atomic
def add_omsat3_survey(apps, schema_editor):
    Survey = apps.get_model(app_name, 'Survey')
    survey = Survey.objects.create(
        name="OMSAT 3* - Ottawský dotazník mentálních dovedností ve sportu",
        description=omsat3_description,
    )
    # add_omsat3_categories(apps, survey.id)
    Category = apps.get_model(app_name, 'Category')
    omsat3_categories = [
        Category(name="ZVLÁDÁNÍ STRACHU", survey=survey,
                 description="""Nejprve prosím přečtěte: Zvládání strachu je dovednost zvládat sportovní situace,
                 teré vyvolávají strach nebo jsou potenciálně ohrožující."""),
        Category(name="MENTÁLNÍ TRÉNINK", survey=survey,
                 description="""Nejprve prosím přečtěte: Mentální trénink je proces, kdy sportovec mentálně procvičuje 
                 fyzické dovednosti, hru, nebo části svého výkonu bez pohybu jakékoliv části jeho těla.
                 Toho může být dosaženo například přemýšlením nad hrou. Je možné si výkon také vizualizovat,
                 či jej procítit."""),
        Category(name="PLÁNOVÁNÍ SOUTĚŽE", survey=survey,
                 description="""Nejprve prosím přečtěte: Plánování soutěže znamená, 
                 že si jedinec vyčlení určitý čas k promyšlení plánů, které budou provázet jeho myšlenky, emoce a akce, 
                 a to jak před, během či po soutěži."""),
    ]
    for category in omsat3_categories:
        category.save()
    # Category.objects.bulk_create(omsat3_categories)
    # add_omsat3_likert_scales(apps, survey.id)
    LikertScale = apps.get_model(app_name, 'LikertScale')
    omsat3_likert_scales = [
        LikertScale(name="LS1", survey=survey),
        LikertScale(name="LS2", survey=survey),
        LikertScale(name="LS3", survey=survey),
        LikertScale(name="LS4", survey=survey),
        LikertScale(name="LS5", survey=survey),
        LikertScale(name="LS6", survey=survey),
        LikertScale(name="LS7", survey=survey, category=omsat3_categories[0]),
        LikertScale(name="LS8", survey=survey, category=omsat3_categories[1]),
        LikertScale(name="LS9", survey=survey, category=omsat3_categories[2]),
    ]
    for likert_scale in omsat3_likert_scales:
        likert_scale.save()
    # LikertScale.objects.bulk_create(omsat3_likert_scales)
    # add omsat3 questions
    Question = apps.get_model(app_name, 'Question')
    question_order_generator = integer_sequence(300)
    omsat3_questions = [
        Question(text="Sport:", order=next(question_order_generator), required=True, type=SHORT_TEXT,
                 survey=survey),
        Question(text="Současná úroveň, na které provozujete svůj sport:", order=next(question_order_generator),
                 required=True, type=RADIO, survey=survey, choices=omsat3_current_sport_level_choices),
        Question(text="Nejvyšší úroveň, na které jste provozoval/a svůj sport:", order=next(question_order_generator),
                 required=True, type=RADIO, survey=survey, choices=omsat3_max_sport_level_choices),
        Question(text="Nejvyšší stupeň dokončeného vzdělání:", order=next(question_order_generator), required=True,
                 type=SELECT, survey=survey, choices=omsat3_education_choices),
        # LS1
        Question(text="Stanovuji si denní tréninkové cíle.", order=next(question_order_generator), required=True,
                 type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[0]),
        Question(text="Věřím, že dokážu uspět ve svém sportu navzdory překážkám, na které narazím.",
                 order=next(question_order_generator), required=True, type=LIKERT_SCALE, survey=survey,
                 choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[0]),
        Question(text="Je pro mne snadné se uvolnit.", order=next(question_order_generator), required=True,
                 type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[0]),
        Question(text="Když jsem při tréninku unavený/á, umím navýšit svou úroveň energie.",
                 order=next(question_order_generator), required=True, type=LIKERT_SCALE, survey=survey,
                 choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[0]),
        Question(text="Mívám problémy s výkonností, protože jsem příliš nervózní.",
                 order=next(question_order_generator), required=True, type=LIKERT_SCALE, survey=survey,
                 choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[0]),
        Question(text="Jsem odhodlaný/á se svým sportem nikdy nepřestat.", order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[0]),
        # LS2
        Question(text="Ztrácím koncentraci během důležitých soutěží/zápasů.", order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[1]),
        Question(text="Když imaginuji, je pro mne snadné si vytvářet představy.",
                 order=next(question_order_generator), required=True,
                 type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[1]),
        Question(text="Stanovuji si náročné, ale dosažitelné cíle.", order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[1]),
        Question(text="Jednám sebejistě i v obtížných sportovních situacích.",
                 order=next(question_order_generator), required=True,
                 type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[1]),
        Question(text="Během soutěže/zápasu mé tělo zbytečně ztuhne.",
                 order=next(question_order_generator), required=True, type=LIKERT_SCALE, survey=survey,
                 choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[1]),
        Question(text="Ztrácím koncentraci během každodenního tréninku.", order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[1]),
        # LS3
        Question(text="Jsem odhodlaný/á stát se vynikajícím sportovcem ve své disciplíně.",
                 order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[2]),
        Question(text="Když imaginuji, je pro mne snadné měnit představy ve své mysli.",
                 order=next(question_order_generator), required=True,
                 type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[2]),
        Question(text="Umím si vědomě snížit napětí ve svalech.", order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[2]),
        Question(text="Když se při soutěží/zápase cítím příliš uvolněný/á, umím zvýšit svou energetickou hladinu.",
                 order=next(question_order_generator), required=True,
                 type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[2]),
        Question(text="Při soutěži/zápase vedou mé chyby často k dalším chybám.",
                 order=next(question_order_generator), required=True, type=LIKERT_SCALE, survey=survey,
                 choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[2]),
        Question(text="Stanovuji si cíle, které přispívají ke zlepšování běžných složek mého sportovního výkonu.",
                 order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[2]),
        # LS4
        Question(text="Když imaginuji, mé představy jsou jasné.",
                 order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[3]),
        Question(
            text="Když mě něco v průběhu soutěže/zápasu rozruší, je pro mne těžké získat znovu kontrolu sám/sama nad sebou.",
            order=next(question_order_generator), required=True,
            type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
            likert_scale=omsat3_likert_scales[3]),
        Question(text="Věřím, že je v mých možnostech dosáhnout svých cílů.", order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[3]),
        Question(text="Je pro mne snadné se rychle uvolnit.",
                 order=next(question_order_generator), required=True,
                 type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[3]),
        Question(text="Jsem ochotný/á obětovat většinu ostatních věcí, abych vynikl/a ve svém sportu.",
                 order=next(question_order_generator), required=True, type=LIKERT_SCALE, survey=survey,
                 choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[3]),
        Question(text="V některých situacích v tréninku je pro mne těžké se soustředit.",
                 order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[3]),
        # LS5
        Question(text="Velké publikum mne při soutěži/zápase znervózňuje.",
                 order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[4]),
        Question(
            text="Když imaginuji, ve svých představách dokážu cítit pohyby.",
            order=next(question_order_generator), required=True,
            type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
            likert_scale=omsat3_likert_scales[4]),
        Question(text="V průběhu soutěže/zápasu je pro mne těžké dostat z hlavy nečekanou událost.",
                 order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[4]),
        Question(text="Podávám lepší výkon při tréninku než v soutěži/zápase.",
                 order=next(question_order_generator), required=True,
                 type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[4]),
        Question(text="Dokážu sám sebe snadno nabudit na optimální úroveň, při které podávám nejlepší výkony.",
                 order=next(question_order_generator), required=True, type=LIKERT_SCALE, survey=survey,
                 choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[4]),
        Question(text="Mám problémy s udržením koncentrace po dobu celé/celého soutěže/zápasu.",
                 order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[4]),
        # LS6
        Question(text="Jsem odhodlanější zlepšovat se ve svém sportu více, než v čemkoliv jiném v mém životě.",
                 order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[5]),
        Question(
            text="Mé cíle mě motivují pracovat usilovněji.",
            order=next(question_order_generator), required=True,
            type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
            likert_scale=omsat3_likert_scales[5]),
        Question(text="Umím se účinně zklidnit/ uvolnit během kritických momentů v zápase.",
                 order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[5]),
        Question(text="Během tréninku příliš hloubám nad svými chybami.",
                 order=next(question_order_generator), required=True,
                 type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[5]),
        Question(text="Pokud se cítím v průběhu soutěže/zápasu bez energie, jsem schopný/á se snadno nabudit.",
                 order=next(question_order_generator), required=True, type=LIKERT_SCALE, survey=survey,
                 choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[5]),
        Question(text="Jsem sebejistý/á ve většině aspektů svého výkonu.",
                 order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[5]),
        # LS7
        Question(text="V mém sportu se vyskytuje řada věcí, které jsou pro mne ohrožujících a ze kterých mám strach.",
                 order=next(question_order_generator), category=omsat3_categories[0],
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[6]),
        Question(
            text="Je pro mne těžké trénovat kvůli strachu, který souvisí s mým sportem.",
            order=next(question_order_generator), required=True, category=omsat3_categories[0],
            type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
            likert_scale=omsat3_likert_scales[6]),
        Question(text="Bojím se prohrát.", category=omsat3_categories[0],
                 order=next(question_order_generator),
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[6]),
        Question(text="Je pro mne těžké v rámci tréninku získat kontrolu nad věcmi a omezit tak své obavy.",
                 order=next(question_order_generator), required=True, category=omsat3_categories[0],
                 type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[6]),
        # LS8
        Question(text="Mentální trénink svého sportu provádím každodenně.",
                 order=next(question_order_generator), category=omsat3_categories[1],
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[7]),
        Question(
            text="Můj mentální trénink je plánovaný.",
            order=next(question_order_generator), required=True, category=omsat3_categories[1],
            type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
            likert_scale=omsat3_likert_scales[7]),
        Question(text="Provádím mentální trénink svého sportu s představou maximálního výkonu.",
                 order=next(question_order_generator), category=omsat3_categories[1],
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[7]),
        Question(text="Provádím mentální trénink kritických soutěžních/zápasových situací.",
                 order=next(question_order_generator), required=True, category=omsat3_categories[1],
                 type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[7]),
        # LS9
        Question(text="Plánuji určitý soubor činností, které provádím před soutěží/zápasem.",
                 order=next(question_order_generator), category=omsat3_categories[2],
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[8]),
        Question(
            text="Plánuji si stálou sadu věcí, které si před soutěží/zápasem promyslím.",
            order=next(question_order_generator), required=True, category=omsat3_categories[2],
            type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
            likert_scale=omsat3_likert_scales[8]),
        Question(text="Plánuji si stálý seznam věcí, které provedu v průběhu soutěže/zápasu.",
                 order=next(question_order_generator), category=omsat3_categories[2],
                 required=True, type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[8]),
        Question(text="Mám plán, který zahrnuje určitá pomocná slova, které si říkám při soutěži/zápase.",
                 order=next(question_order_generator), required=True, category=omsat3_categories[2],
                 type=LIKERT_SCALE, survey=survey, choices=omsat3_likert_scale_choices,
                 likert_scale=omsat3_likert_scales[8]),
    ]
    Question.objects.bulk_create(omsat3_questions)


class Migration(migrations.Migration):
    dependencies = [
        ('sportdiag', '0014_auto_20220203_1336'),
    ]

    operations = [
        migrations.RunPython(add_omsat3_survey),
    ]
