# Generated by Django 3.2.8 on 2024-05-26 12:33

from django.db import migrations
from django.db import transaction
from sportdiag.models import Survey as _Survey
from sportdiag.models import Question as _Question
from bp.utils.migrations import integer_sequence

app_name = "sportdiag"
survey_name = "Zkrácená škála dispozičního flow (S DFS)"


@transaction.atomic
def add_sdfs_survey(apps, schema_editor):
    Survey = apps.get_model(app_name, "Survey")
    survey = Survey.objects.create(
        name=survey_name,
        description="""Zkrácená škála dispozičního flow (SHORT Dispositional Flow Scale) je určena k měření dispozičního flow, s odpovědmi hodnotícími četnost jeho prožívání. Odpovědi by proto měly být zaznamenány v době, která není přímo spojena s účastí na hodnocené činnosti. Jedná se o zkrácenou verzi 36 položkového dotazníku Long Dispositional Flow Scale (DFS-2), kdy každá otázka posuzuje jednu dimenzi dotazníku.""",
        instructions="""Odpovězte prosím na následující otázky ve vztahu na váš prožitek během činnosti či aktivity Otázky níže se vztahují k myšlenkám a pocitům, které během ní prožíváte. Můžete je prožívat někdy, pořád či vůbec. Neexistují žádné správné ani špatné odpovědi. Nejprve popřemýšlejte, jak často vnímáte pocity či myšlenky v průběhu vaší aktivity/činnosti, poté odpovězte na otázky s využitím škály. Pro každou otázku vyberte odpověď, která nejlépe vystihuje váš prožitek.""",
        is_published=True,
        type=_Survey.SDFS,
    )
    # add survey categories
    Category = apps.get_model(app_name, "Category")
    categories = [
        Category(
            # name="Challenge-skill balance",
            name="Rovnováha mezi požadavky situace a schopnostmi jedince (Challenge-Skill Balance)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Action-awareness merging",
            name="Ponoření se do aktivity (Merging of Action and Awareness)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Clear goals",
            name="Jasné cíle (Clear Goals)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Unambiguous feedback",
            name="Bezprostřední zpětná vazba (Unambiguous Feedback)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Total concentration on the task at hand",
            name="Koncentrace pozornosti na samotnou činnost (Concentration on the Task at Hand)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Sense of control",
            name="Pocit kontroly nad provozovanou aktivitou (Sense of Control)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Loss of self-consciousness",
            name="Ztráta sebeuvědomění (Loss of Self-Consciousness)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Transformation of time",
            name="Transformace času (Transformation of Time)",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            # name="Autotelic experience",
            name="Autotelic Experience (Autotelická osobnost)",
            survey=survey,
            description="""DOPLNIT""",
        ),
    ]
    for category in categories:
        category.save()
    # add survey questions
    Question = apps.get_model(app_name, "Question")
    scores = "1,2,3,4,5"
    choices = "nikdy, málokdy, občas, mnohdy, vždy"
    order_number = integer_sequence(100)
    question_number = integer_sequence(10)
    questions = [
        # no category questions
        Question(
            text="Sport",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.SHORT_TEXT,
            survey=survey,
            scores="0",
        ),
        Question(
            text="Současná úroveň, na které provozujete svůj sport",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices="Regionální úroveň, Celonárodní úroveň, Mezinárodní reprezentace, Svůj sport aktivně neprovozuji",
            scores="0,0,0,0",
        ),
        Question(
            text="Nejvyšší úroveň, na které jste provozoval/a svůj sport",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices="Regionální úroveň, Celonárodní úroveň, Mezinárodní reprezentace",
            scores="0,0,0",
        ),
        Question(
            text="Nejvyšší stupeň dokončeného vzdělání",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.SELECT,
            survey=survey,
            choices="Základní, Střední, Vyšší odborné, Vysokoškolské",
            scores="0,0,0,0",
        ),
        Question(
            text="Mé odpovědi se vztahují k následující aktivitě/činnosti",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.SHORT_TEXT,
            survey=survey,
            scores="0",
        ),
        # categorized questions
        Question(
            text="Cítím, že jsem dostatečně schopný/á zvládnout požadavky dané aktivity.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[0],
        ),
        Question(
            text="Dělám věci spontánně a automaticky, aniž bych o tom musel/a přemýšlet.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[1],
        ),
        Question(
            text="Mám jasné ponětí o tom, co chci udělat.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[2],
        ),
        Question(
            text="Mám jasnou představu o tom, jak dobře si vedu v dané aktivitě.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[3],
        ),
        Question(
            text="Plně se soustředím na danou činnost/aktivitu.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[4],
        ),
        Question(
            text="Pociťuji plnou kontrolu nad tím, co dělám.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[5],
        ),
        Question(
            text="Neobávám se toho, co si o mě myslí ostatní.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[6],
        ),
        Question(
            text="Plynutí času mi připadá jiné, než obvykle.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[7],
        ),
        Question(
            text="Mé prožívání dané situace je velmi odměňující/obohacující.",
            number=next(question_number),
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[8],
        ),
    ]
    Question.objects.bulk_create(questions)

@transaction.atomic
def revert_sdfs_survey(apps, schema_editor):
    Survey = apps.get_model(app_name, "Survey")
    survey = Survey.objects.get(name=survey_name)
    if survey:
        survey.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('sportdiag', '0015_alter_survey_type'),
    ]

    operations = [
        migrations.RunPython(add_sdfs_survey, reverse_code=revert_sdfs_survey),
    ]
