# Generated by Django 3.2.8 on 2024-05-26 12:55

from django.db import migrations
from django.db import transaction
from sportdiag.models import Survey as _Survey
from sportdiag.models import Question as _Question
from bp.utils.migrations import integer_sequence

app_name = "sportdiag"
survey_name = "Inventář závodní stavové úzkosti CSAI-2"


@transaction.atomic
def add_csai2_survey(apps, schema_editor):
    Survey = apps.get_model(app_name, "Survey")
    survey = Survey.objects.create(
        name=survey_name,
        description="""CSAI-2 (Competetive state Anxiety Inventory - 2) je 27 položkový dotazník, který měří tři dimenze úzkosti: kognitivní úzkost, somatickou úzkost a sebedůvěru. Kognitivní úzkost se týká myšlenek a obav sportovce z jeho výkonu. Somatická úzkost se týká fyzických příznaků úzkosti sportovce, jako je zvýšená tepová frekvence, svalové napětí a pocení. Sebevědomí se týká víry sportovce ve své schopnosti podat dobrý výkon.""",
        instructions="""V následném dotazníku jsou uvedena tvrzení, kterými sportovci nejčastěji popisují své pocity před důležitým závodem. Každé tvrzení si přečti, a potom vyber odpověď odpovídající tomu, nakolik je toto tvrzení platné pro Tvoji osobu. Vybírat budeš ze čtyř možností. Žádná z odpovědí není správná ani špatná. Odpovídej tedy, prosím, upřímně. Snaž se nestrávit příliš mnoho času nad žádným z uvedených tvrzení, ale vždy vybírej takové hodnocení, které nejlépe vypovídá o tvých pocitech z důležitého závodu.""",
        is_published=True,
        type=_Survey.CSAI2,
    )
    # add survey categories
    Category = apps.get_model(app_name, "Category")
    categories = [
        Category(
            name="Kognitivní úzkost",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            name="Somatická úzkost",
            survey=survey,
            description="""DOPLNIT""",
        ),
        Category(
            name="Sebedůvěra",
            survey=survey,
            description="""DOPLNIT""",
        ),
    ]
    for category in categories:
        category.save()
    # add survey questions
    Question = apps.get_model(app_name, "Question")
    scores = "1,2,3,4"
    scores_desc = "4,3,2,1"
    choices = "vůbec ne, trochu, spíše, velmi"
    order_number = integer_sequence(100)
    questions = [
        # no category questions
        Question(
            text="Sport",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.SHORT_TEXT,
            survey=survey,
            scores="0",
        ),
        Question(
            text="Současná úroveň, na které provozujete svůj sport",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices="Regionální úroveň, Celonárodní úroveň, Mezinárodní reprezentace, Svůj sport aktivně neprovozuji",
            scores="0,0,0,0",
        ),
        Question(
            text="Nejvyšší úroveň, na které jste provozoval/a svůj sport",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices="Regionální úroveň, Celonárodní úroveň, Mezinárodní reprezentace",
            scores="0,0,0",
        ),
        Question(
            text="Nejvyšší stupeň dokončeného vzdělání",
            number=0,
            order=next(order_number),
            required=True,
            type=_Question.SELECT,
            survey=survey,
            choices="Základní, Střední, Vyšší odborné, Vysokoškolské",
            scores="0,0,0,0",
        ),
        # categorized questions
        Question(
            text="Z tohoto závodu mám obavy.",
            number=1,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[0],
        ),
        Question(
            text="Jsem nervózní.",
            number=2,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[1],
        ),
        Question(
            text="Cítím se klidný a uvolněný.",
            number=3,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[2],
        ),
        Question(
            text="Pochybuji o sobě.",
            number=4,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[0],
        ),
        Question(
            text="Cítím se vynervovaný.",
            number=5,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[1],
        ),
        Question(
            text="Cítím se v pohodě.",
            number=6,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[2],
        ),
        Question(
            text="Obávám se, že si nepovedu tak dobře, jak bych mohl(a).",
            number=7,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[0],
        ),
        Question(
            text="Cítím tělesné napětí.",
            number=8,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[1],
        ),
        Question(
            text="Věřím si.",
            number=9,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[2],
        ),
        Question(
            text="Bojím se, že prohraji.",
            number=10,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[0],
        ),
        Question(
            text="Svírá se mi žaludek.",
            number=11,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[1],
        ),
        Question(
            text="Cítím se bezpečně.",
            number=12,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[2],
        ),
        Question(
            text="Bojím se, že to pod tlakem nezvládnu.",
            number=13,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[0],
        ),
        Question(
            text="Tělo mám relaxované.",
            number=14,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores_desc,
            category=categories[1],
        ),
        Question(
            text="Jsem si jist, že tuto výzvu zvládnu.",
            number=15,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[2],
        ),
        Question(
            text="Bojím se, že můj výkon bude slabý.",
            number=16,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[0],
        ),
        Question(
            text="Cítím, jak mi buší srdce.",
            number=17,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[1],
        ),
        Question(
            text="Jsem si jist, že předvedu dobrý výkon.",
            number=18,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[2],
        ),
        Question(
            text="Mám obavy, že nedosáhnu svého cíle.",
            number=19,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[0],
        ),
        Question(
            text="Mám žaludek jako na vodě.",
            number=20,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[1],
        ),
        Question(
            text="Cítím se psychicky uvolněně.",
            number=21,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[2],
        ),
        Question(
            text="Mám obavy, že svým výkonem zklamu ostatní.",
            number=22,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[0],
        ),
        Question(
            text="Mám studené a/nebo zpocené ruce.",
            number=23,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[1],
        ),
        Question(
            text="Věřím si, protože si dokážu představit, jak dosahuji svého cíle.",
            number=24,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[2],
        ),
        Question(
            text="Obávám se, že se nedokážu soustředit.",
            number=25,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[0],
        ),
        Question(
            text="Cítím v těle ztuhlost.",
            number=26,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[1],
        ),
        Question(
            text="Jsem si jist, že to i pod tlakem zvládnu.",
            number=27,
            order=next(order_number),
            required=True,
            type=_Question.RADIO,
            survey=survey,
            choices=choices,
            scores=scores,
            category=categories[2],
        ),
    ]
    Question.objects.bulk_create(questions)


@transaction.atomic
def revert_csai2_survey(apps, schema_editor):
    Survey = apps.get_model(app_name, "Survey")
    survey = Survey.objects.get(name=survey_name)
    if survey:
        survey.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sportdiag", "0017_alter_survey_type"),
    ]

    operations = [
        migrations.RunPython(add_csai2_survey, reverse_code=revert_csai2_survey),
    ]
