# Generated by Django 3.2.8 on 2024-05-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportdiag', '0018_demo_data_csai2_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='type',
            field=models.CharField(choices=[('ACSI-28-REFEREE', 'ASCI-28 pro rozhodčí'), ('ACSI-28-ATHLETE', 'ASCI-28 pro sportovce'), ('PCDEQ', 'PCDEQ'), ('VMIQ-2', 'VIMQ-2'), ('OMSAT-3*', 'OMSAT-3* modifikovaná verze'), ('GEQ-CZ-V1', 'GEQ-CZ V1'), ('S-FSS', 'S FSS'), ('S-DFS', 'S DFS'), ('CSAI-2', 'CSAI-2')], default='ACSI-28-REFEREE', max_length=60, verbose_name='Typ/Metoda'),
        ),
    ]
