version: "3.4"
services:
  db:
    image: postgres:14.4-alpine
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/db/psql-init/db.sql:/docker-entrypoint-initdb.d/db.sql
      - pgdata:/var/lib/postgresql/data/
  sportdiag_web_app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      target: prod
    restart: always
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE_PROD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - media:/home/sportdiag/src/media
      - static_files:/home/sportdiag/src/collected_static
  nginx:
    build: ./docker/nginx
    ports:
      - 80:80 # 1337 for prod image localhost testing
    depends_on:
      - sportdiag_web_app
    volumes:
      - media:/home/sportdiag/src/media
      - static_files:/home/sportdiag/src/collected_static

volumes:
  pgdata:
  media:
  static_files:
