# Generated by Django 3.2.8 on 2022-04-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_demo_data_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmed_by_staff',
            field=models.BooleanField(default=False, verbose_name='schválený hlavním výzkumníkem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False,
                                      help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                                      verbose_name='active'),
        ),
    ]
