# Generated by Django 3.2.8 on 2023-11-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_demo_data_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='nationality',
            field=models.CharField(choices=[('CZ', 'ČR'), ('SK', 'SK')], default='CZ', max_length=3, verbose_name='státní příslušnost'),
        ),
    ]
